throw (new ursa.exceptions.exception)
